sitename: "sourcenode"
siteurl: "https://fabiomurer.org"
gitrepo: "https://github.com/zwirgioIlredelCodice/personal-site"
language: en


navbar:
  - name: Home
    url:  .
  - name: About
    url: about/
